### PR TITLE
Basic interaction assets were relocated

### PR DESCRIPTION
**Pull request by Gusinuhe**
### Description

The VR interaction assets were relocated from the XR Component into Basic Interaction so other VR implementations could use them.

### Type of change

- [x] New feature (non-breaking change which adds functionality)

### CODE REVIEW

**Comment by tomwim** [comment]
I have missing prefabs in the Reticle and missing materials in the Anchor when I have https://github.com/Innoactive/XR-Interaction-Component/pull/91 checked out as well

**Comment by Gusinuhe** [comment]
> I have missing prefabs in the Reticle and missing materials in the Anchor when I have [Innoactive/XR-Interaction-Component#91](https://github.com/Innoactive/XR-Interaction-Component/pull/91) checked out as well

To me it works fine, did you update a project or started a new from scratch?

**Comment by tomwim** [comment]
> > I have missing prefabs in the Reticle and missing materials in the Anchor when I have [Innoactive/XR-Interaction-Component#91](https://github.com/Innoactive/XR-Interaction-Component/pull/91) checked out as well
> 
> To me it works fine, did you update a project or started a new one from scratch?

Updated the project (actually 2 different ones)

**Comment by tomwim** [comment]
I see a `teleportHighlight.fbx` but not a prefab which I guess is missing in the `TeleportReticle`

**Comment by Gusinuhe** [comment]
> I see a `teleportHighlight.fbx` but not a prefab which I guess is missing in the `TeleportReticle`
> 
> I'll restart Unity and then also set up a new project

The prefab must be on the Resources folder.

**Comment by tomwim** [comment]
> > I see a `teleportHighlight.fbx` but not a prefab which I guess is missing in the `TeleportReticle`
> > I'll restart Unity and then also set up a new project
> 
> The prefab must be on the Resources folder.
> 
> image

Damn...all meta files were changed for some reason and apparently pointed somewhere else. looks good now

**Comment by Gusinuhe** [comment]
> > > I see a `teleportHighlight.fbx` but not a prefab which I guess is missing in the `TeleportReticle`
> > > I'll restart Unity and then also set up a new project
> > 
> > 
> > The prefab must be on the Resources folder.
> > image
> 
> Damn...all meta files were changed for some reason and apparently pointed somewhere else. looks good now

It would be good to see what would happen with old projects, I'll try later with one from our customers 😕

**Review by SimonTheSourcerer — APPROVED** [review]

**Review by tomwim — APPROVED** [review]

**Comment by Gusinuhe** [comment]
I ran a sanity check to see if there could be anything broken on old projects, it seems fine.

**Pull request merged**
