### PR TITLE
Feature/add help html link

### PR DESCRIPTION
**Pull request by JulieAtInnoactive**
### Description
added help attribute

**Fixes**: # (issue)

### Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

### How Has This Been Tested?

**Test Configuration**:

### Checklist

- [ ] My code follows the [Coding Conventions](#coding-conventions)
- [ ] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by tomwim** [comment]
Needs updating to latest changes from develop. Will test as soon as this is done

**Review by tomwim — APPROVED** [review]

**Review by Gusinuhe — APPROVED** [review]

**Comment by Gusinuhe** [comment]
Please provide a proper description with links to other interdependencies.

**Comment by tomwim** [comment]
p!

**Pull request merged**
